name: 'Setup'
description: 'Setup for Otter Library'

inputs:
  enable-build-cache:
    description: 'Enable Cache'
    required: false
    default: 'false'
  enable-test-app-cache:
    description: 'Enable Cache for test-app'
    required: false
    default: 'false'
  cache-build-identifier:
    description: 'Custom identifier to build cache key'
    required: false
    default: 'global'

runs:
  using: "composite"
  steps:
    - uses: actions/setup-node@v3
      with:
        node-version: 18
    - name: Cache dependencies
      uses: actions/cache@v3
      with:
        path: |
          .yarn/cache
          .yarn/unplugged
          .pnp.cjs
          .pnp.loader.mjs
        key: ${{ runner.os }}-deps-${{ hashFiles('yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-deps
          ${{ runner.os }}
    - name: Cache build
      if: inputs.enable-build-cache == 'true'
      uses: actions/cache@v3
      env:
        hash: ${{ hashFiles('package.json', 'tsconfig.base.json', 'tsconfig.build.json', 'nx.json') }}
      with:
        path: |
          .cache/nx
          .cache/angular
          .angular/cache
          node_modules/.cache/ng-packagr
          node_modules/.cache/nx
        key: ${{ runner.os }}-build-${{ env.hash }}-${{ inputs.cache-build-identifier }}
        restore-keys: |
          ${{ runner.os }}-build-${{ env.hash }}-${{ inputs.cache-build-identifier }}
          ${{ runner.os }}-build-${{ env.hash }}-global
          ${{ runner.os }}-build-${{ env.hash }}
          ${{ runner.os }}-build
          ${{ runner.os }}
    - run: echo "date=$(date +'%Y-%m')" >> $GITHUB_ENV
      shell: bash
    - name: Cache test-app yarn
      if: inputs.enable-test-app-cache == 'true'
      uses: actions/cache@v3
      with:
        path: |
          .cache/test-app
          !.cache/test-app/v6/npm-@ama-sdk*
          !.cache/test-app/v6/npm-@ama-terasu*
          !.cache/test-app/v6/npm-@o3r*
        key: ${{ runner.os }}-test-app-${{ env.date }}
    - name: Install
      shell: bash
      run: yarn install
